---
- hosts: localhost
  tasks:
    - name: Install Docker
      command: snap install docker

    - name: Clone repository from GITHUB
      command: git clone https://github.com/JustasCiapas/TStask.git

    - name: Go to repository and Build docker container
      command: docker build -t app .
      args:
        chdir: TStask/

    - name: Run Docker container
      command: docker run -d -p 80:80 app
